### PR TITLE
bahmni compose profile bahmni-lite

### PR DESCRIPTION
**Pull request by jeffvun**

### CODE REVIEW

**Comment by jeffvun** [comment]
upgrading the compose profile from emr (default) to bahmni lite

**Comment by mohan-13** [comment]
@jeffvun Thanks for your PR. We have kept emr as the default profile to make sure that only minimal set of services come up by default. If you are intending to run bahmni-lite as a whole, please make changes to .env in your implementation. Thanks

**Comment by jeffvun** [comment]
> @jeffvun Thanks for your PR. We have kept emr as the default profile to make sure that only minimal set of services come up by default. If you are intending to run bahmni-lite as a whole, please make changes to .env in your implementation. Thanks

**Comment by jeffvun** [comment]
As mentioned by @mohan-13  just update your env file in case you want to use a different setup (emr, bahmni-lie, bahmni-standard, etc...)

**Pull request closed without merging**
