### PR TITLE
BAH-2791: Ensure that when mart/metabase are chosen, the right services come up

### PR DESCRIPTION
**Pull request by gsluthra**
…. Also added some missing services into emr profile - like lablite and implementer interface

### CODE REVIEW

**Comment by gsluthra** [comment]
When metabase comes up, it needs to have access to openmrs db. So added that in the profile. When Mart comes up, all metabase & openmrs db should also come up. In general, advice to people will be to use profile `bahmni-mart` for analytics purposes.

**Comment by gsluthra** [comment]
JIRA issue: https://bahmni.atlassian.net/browse/BAH-2791

**Comment by mohan-13** [comment]
@gsluthra The changes around metabase / bahmni-mart looks good to me.  

But since we agreed that `emr` can be the lightest profile for quick start and for development purposes, do we need to add lab-lite and implementer-interface to emr profile? 
[Ref Diagram](https://github.com/Bahmni/bahmni-diagrams/pull/5/files)

**Comment by gsluthra** [comment]
yes.. emr = Electronic medical record.. meaning.. all EMR functionalities. Lab Lite and Implementer interface are seen as EMR components. I am hoping they are lightweight too by themselves, unlike Odoo/DCM4chee which are big. Ideally everything in "Clinical" should be seen as emr.

**Comment by gsluthra** [comment]
I just go to know from @pajmera4 , that MART needs openmrs SERVICE also, so I will need to push a new commit with "bahmni-mart" added to openmrs service also. I hope if i execute `docker compose --profile bahmni-mart up -d` when OpenMRS is already running, will this docker compose bring up a second openmrs service? Any idea? That would be bad!

**Comment by mohan-13** [comment]
> I just go to know from @pajmera4 , that MART needs openmrs SERVICE also, so I will need to push a new commit with "bahmni-mart" added to openmrs service also. I hope if i execute `docker compose --profile bahmni-mart up -d` when OpenMRS is already running, will this docker compose bring up a second openmrs service? Any idea? That would be bad!

No Gurpreet. If the service is running it will just use the same. It will not spun up a new instance

**Comment by gsluthra** [comment]
@mohan-13 - thanks. I have pushed the changes for bahmni-mart profile to be connected to openmrs. Can you plz review and merge. thanks!

**Review by mohan-13 — APPROVED** [review]

**Pull request merged**
