### PR TITLE
BAH-3030 | Added env for openmrs container

### PR DESCRIPTION
**Pull request by atish160384**
Added SMS URL in env's

### CODE REVIEW

**Comment by gsluthra** [comment]
Shouldn't this also go in Bahmni-standard subfolder?

**Comment by gsluthra** [comment]
Is there another PR for SMS_URL reading in docker image?

**Comment by atish160384** [comment]
> 

yah Gurpreet will be adding the same in standard too
To read the env SMS_URI i had added a PR in [openmrs_distro_bahmni https://github.com/Bahmni/openmrs-distro-bahmni/pull/134](url) which will be used by bahmni-core omod

**Comment by atish160384** [comment]
New changes will be pushed into 2962 branch

**Pull request closed without merging**
